// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: NetMsg.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace PEProtocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NetMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"head")]
        public Head Head { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"body")]
        public Body Body { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Head : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cmd")]
        public Cmd Cmd { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"error_code")]
        public ErrorCode ErrorCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Body : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player_data")]
        public PlayerData PlayerData { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_login")]
        public RequestLogin RequestLogin { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"response_login")]
        public ResponseLogin ResponseLogin { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"request_rename")]
        public RequestRename RequestRename { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"response_rename")]
        public ResponseRename ResponseRename { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"request_guide")]
        public RequestGuide RequestGuide { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"response_guide")]
        public ResponseGuide ResponseGuide { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"request_strengthen")]
        public RequestStrengthen RequestStrengthen { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"response_strengthen")]
        public ResponseStrengthen ResponseStrengthen { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"send_chat")]
        public SendChat SendChat { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"push_chat")]
        public PushChat PushChat { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"request_buy")]
        public RequestBuy RequestBuy { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"response_buy")]
        public ResponseBuy ResponseBuy { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"push_power")]
        public PushPower PushPower { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"request_task")]
        public RequestTask RequestTask { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"response_task")]
        public ResponseTask ResponseTask { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"push_task")]
        public PushTask PushTask { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"request_dungeon")]
        public RequestDungeon RequestDungeon { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"response_dungeon")]
        public ResponseDungeon ResponseDungeon { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"request_end_dungeon")]
        public RequestEndDungeon RequestEndDungeon { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"response_end_dungeon")]
        public ResponseEndDungeon ResponseEndDungeon { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"password")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"exp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Exp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"coin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Coin { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"diamond", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Diamond { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"crystal", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Crystal { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"hp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Hp { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"ad", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Ad { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"ad_def", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int AdDef { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"ap", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Ap { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"ap_def", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int ApDef { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"critical", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Critical { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"pierce", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Pierce { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"dodge", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Dodge { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"guide_id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int GuideId { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"dungeon_id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int DungeonId { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"task_data")]
        public global::System.Collections.Generic.List<TaskData> TaskDatas { get; set; } = new global::System.Collections.Generic.List<TaskData>();

        [global::ProtoBuf.ProtoMember(21, Name = @"strengthen_data")]
        public global::System.Collections.Generic.List<StrengthenData> StrengthenDatas { get; set; } = new global::System.Collections.Generic.List<StrengthenData>();

        [global::ProtoBuf.ProtoMember(22, Name = @"power", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Power { get; set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"leave_time")]
        public double LeaveTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"task_id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int TaskId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"progress", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Progress { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"max_count", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int MaxCount { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"finished")]
        public bool Finished { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StrengthenData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"strengthen_type")]
        public StrengthenType StrengthenType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestLogin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"password")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseLogin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player_data")]
        public PlayerData PlayerData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestRename : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseRename : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestGuide : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"guide_id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int GuideId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseGuide : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"coin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Coin { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Exp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"guide_id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int GuideId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestStrengthen : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"strengthen_type")]
        public StrengthenType StrengthenType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseStrengthen : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ad", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Ad { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ad_def", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int AdDef { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ap", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Ap { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ap_def", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int ApDef { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"coin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Coin { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"crystal", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Crystal { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"hp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Hp { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"strengthen_arr")]
        public global::System.Collections.Generic.List<StrengthenData> StrengthenArrs { get; set; } = new global::System.Collections.Generic.List<StrengthenData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendChat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"chat")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Chat { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PushChat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"chat")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Chat { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestBuy : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cost", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Cost { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseBuy : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"coin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Coin { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cost", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Cost { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"diamond", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Diamond { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"power", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Power { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PushPower : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"power", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Power { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestTask : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseTask : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"coin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Coin { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Exp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"task_list")]
        public global::System.Collections.Generic.List<TaskData> TaskLists { get; set; } = new global::System.Collections.Generic.List<TaskData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PushTask : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"task_list")]
        public global::System.Collections.Generic.List<TaskData> TaskLists { get; set; } = new global::System.Collections.Generic.List<TaskData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestDungeon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dungeon_id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int DungeonId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseDungeon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dungeon_id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int DungeonId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"power", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Power { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestEndDungeon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"win")]
        public bool Win { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"dungeon_id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int DungeonId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"rest_hp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int RestHp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"cost_time", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int CostTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseEndDungeon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"win")]
        public bool Win { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"dungeon_id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int DungeonId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"rest_hp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int RestHp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"cost_time", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int CostTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"coin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Coin { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"exp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Exp { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"crystal", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Crystal { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"dungeon", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Dungeon { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"CMD")]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_NONE")]
        CmdNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_REQUEST_LOGIN")]
        CmdRequestLogin = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_RESPONSE_LOGIN")]
        CmdResponseLogin = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_REQUEST_RENAME")]
        CmdRequestRename = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_RESPONSE_RENAME")]
        CmdResponseRename = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_REQUEST_GUIDE")]
        CmdRequestGuide = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_RESPONSE_GUIDE")]
        CmdResponseGuide = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_REQUEST_STRENGTHEN")]
        CmdRequestStrengthen = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_RESPONSE_STRENGTHEN")]
        CmdResponseStrengthen = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_SEND_CHAT")]
        CmdSendChat = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_PUSH_CHAT")]
        CmdPushChat = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_REQUEST_BUY")]
        CmdRequestBuy = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_RESPONSE_BUY")]
        CmdResponseBuy = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_PUSH_POWER")]
        CmdPushPower = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_REQUEST_TASK")]
        CmdRequestTask = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_RESPONSE_TASK")]
        CmdResponseTask = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_PUSH_TASK")]
        CmdPushTask = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_REQUEST_DUNGEON")]
        CmdRequestDungeon = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_RESPONSE_DUNGEON")]
        CmdResponseDungeon = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_REQUEST_END_DUNGEON")]
        CmdRequestEndDungeon = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"CMD_RESPONSE_END_DUNGEON")]
        CmdResponseEndDungeon = 20,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ErrorCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_CODE_NONE")]
        ErrorCodeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_CODE_ACCOUNT_IS_ONLINE")]
        ErrorCodeAccountIsOnline = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_CODE_WRONG_PASSWORD")]
        ErrorCodeWrongPassword = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_CODE_NAME_EXIST")]
        ErrorCodeNameExist = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_CODE_UPDATA_DATABASE_ERROR")]
        ErrorCodeUpdataDatabaseError = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_CODE_SERVER_DATA_ERROR")]
        ErrorCodeServerDataError = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_CODE_CLIENT_DATA_ERROR")]
        ErrorCodeClientDataError = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_CODE_LACK_LEVEL")]
        ErrorCodeLackLevel = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_CODE_LACK_COIN")]
        ErrorCodeLackCoin = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_CODE_LACK_CRYSTAL")]
        ErrorCodeLackCrystal = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_CODE_LACK_DIAMOND")]
        ErrorCodeLackDiamond = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_CODE_LACK_POWER")]
        ErrorCodeLackPower = 11,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum StrengthenType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"STRENGTHEN_TYPE_HEAD")]
        StrengthenTypeHead = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"STRENGTHEN_TYPE_BODY")]
        StrengthenTypeBody = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"STRENGTHEN_TYPE_WAIST")]
        StrengthenTypeWaist = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"STRENGTHEN_TYPE_HAND")]
        StrengthenTypeHand = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"STRENGTHEN_TYPE_LEG")]
        StrengthenTypeLeg = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"STRENGTHEN_TYPE_FEET")]
        StrengthenTypeFeet = 5,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
